FROM amd64/openjdk:18
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

ENV SPRING_PROFILES_ACTIVE=prod
ENV ITFLOW_TIMEZONE ${ITFLOW_TIMEZONE}
ENV ITFLOW_DB_HOST ${ITFLOW_DB_HOST}
ENV ITFLOW_DB_SSL ${ITFLOW_DB_SSL}
ENV ITFLOW_MAIL_USER ${ITFLOW_MAIL_USER}
ENV ITFLOW_MAIL_PWD ${ITFLOW_MAIL_PWD}
ENV ITFLOW_MAIL_HOST ${ITFLOW_MAIL_HOST}
ENV ITFLOW_MAIL_PORT ${ITFLOW_MAIL_PORT}
ENV ITFLOW_MAIL_TLS ${ITFLOW_MAIL_TLS}
ENV ITFLOW_MAIL_SSL ${ITFLOW_MAIL_SSL}
ENV ITFLOW_MAIL_SSL_PROTOCOLS ${ITFLOW_MAIL_SSL_PROTOCOLS}
ENV ITFLOW_JWT_SECRET ${ITFLOW_JWT_SECRET}
ENV ITFLOW_JWT_EXPIRE ${ITFLOW_JWT_EXPIRE}

ENTRYPOINT ["java","-jar","/app.jar"]