FROM amd64/openjdk:18
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

ENV SPRING_PROFILES_ACTIVE=prod
ENV TIMEZONE ${TIMEZONE}
ENV REDIS_HOST ${REDIS_HOST}
ENV DB_HOST ${DB_HOST}
ENV DB_PORT ${DB_PORT}
ENV DB_NAME ${DB_NAME}
ENV DB_USE_SSL ${DB_USE_SSL}
ENV DB_USER ${DB_USER}
ENV DB_PWD ${DB_PWD}
ENV MAIL_USER ${MAIL_USER}
ENV MAIL_PWD ${MAIL_PWD}
ENV MAIL_SERVER ${MAIL_SERVER}
ENV MAIL_PORT ${MAIL_PORT}
ENV MAIL_AUTH ${MAIL_AUTH}
ENV ENABLE_TLS ${ENABLE_TLS}
ENV ENABLE_SSL ${ENABLE_SSL}
ENV MAIL_SSL_PROTOCOLS ${MAIL_SSL_PROTOCOLS}
ENV JWT_SECRET ${JWT_SECRET}
ENV JWT_EXPIRE ${JWT_EXPIRE}

ENTRYPOINT ["java","-jar","/app.jar"]