app:
  version: '@project.version@'
  timezone: 'America/Asuncion'
  login:
    attempts: 5
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  ssl:
    key-store-type: PKCS12
    key-store: itflow.p12
    key-store-password: itflow
    key-alias: itflow
    enabled: false
  security:
    require-ssl: false
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/itflow?useSSL=false&serverTimezone=app.timezone
    username: itflow
    password: itflow
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart.max-file-size: 5MB
    multipart.max-request-size: 5MB
  mail:
    username: mailtrap_username
    password: mailtrap_password
    host: smtp.mailtrap.io
    port: 25
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false
            protocols: 'TLSv1.2'
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
         format_sql: true
         dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    validate-on-migrate: true
  redis:
    host: localhost
    port: 6379
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    url: /v3/api-docs/
    filter: false
    path: /
    doc-expansion: none
logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        boot:
          autoconfigure: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%clr(%5p)] %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: ${user.home}/logs/itflow/itflow-api.log
  logback:
    rollingpolicy:
      max-file-size: 20MB
      max-history: 10
jwt:
  secret: "A2DAF8D98E959FB4F47FA167146A37736EB4227FD6996FB72A19E2B65E"
  expire: 720
