app:
  version: '@project.version@'
  timezone: 'America/Asuncion'
  login:
    attempts: 5
spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    locations: classpath:/db/specific/h2
  mail:
    username: username
    password: password
    host: smtp.mailtrap.io
    port: 25
    protocol: smtp
jwt:
  secret: "123456"
  expire: 60