app:
  version: '@project.version@'
  timezone: 'America/Asuncion'
  login:
    attempts: 5
spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: true
  flyway:
    locations: classpath:/db/specific/h2
  mail:
    username: username
    password: password
    host: smtp.mailtrap.io
    port: 25
    protocol: smtp
  jackson:
    mapper:
      default-view-inclusion: true
jwt:
  secret: "A2DAF8D98E959FB4F47FA167146A37736EB4227FD6996FB72A19E2B65E"
  expire: 60