app:
  version: '@project.version@'
  timezone: ${TIMEZONE}
  login:
    attempts: 5
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
#  ssl:
#    key-store-type: PKCS12
#    key-store: itflow.p12
#    key-store-password: itflow
#    key-alias: itflow
#    enabled: false
#  security:
#    require-ssl: false
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=${DB_USE_SSL}&serverTimezone=app.timezone
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart.max-file-size: 5MB
    multipart.max-request-size: 5MB
  mail:
    username: ${MAIL_USER}
    password: ${MAIL_PWD}
    host: ${MAIL_SERVER}
    port: ${MAIL_PORT}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH}
          starttls:
            enable: ${ENABLE_TLS}
          ssl:
            enable: ${ENABLE_SSL}
            protocols: ${MAIL_SSL_PROTOCOLS}
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    validate-on-migrate: true
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    url: /v3/api-docs/
    filter: false
    path: /
    doc-expansion: none
logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: ERROR
      springframework:
        boot:
          autoconfigure: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%clr(%5p)] %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: ${user.home}/logs/itflow/itflow-api.log
  logback:
    rollingpolicy:
      max-file-size: 20MB
      max-history: 10
jwt:
  secret: ${JWT_SECRET}
  expire: ${JWT_EXPIRE}
