#  ssl:
#    key-store-type: PKCS12
#    key-store: itflow.p12
#    key-store-password: itflow
#    key-alias: itflow
#    enabled: false
spring:
  datasource:
    url: jdbc:h2:mem:test;DATABASE_TO_UPPER=false;
  mail:
    username: username
    password: password
    host: sandbox.smtp.mailtrap.io
    port: 25
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false
            protocols: 'TLSv1.2'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    root: DEBUG
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        boot:
          autoconfigure: INFO
jwt:
  secret: "A2DAF8D98E959FB4F47FA167146A37736EB4227FD6996FB72A19E2B65E"
  expire: 720
