INSERT INTO "ACCOUNT" ("FULL_NAME", "AVATAR", "EMAIL", "USERNAME", "PASSWORD", "LAST_LOGIN_DATE", "JOIN_DATE", "ACTIVE",
                       "NON_LOCKED") VALUES ('ADMINISTRATOR', '', 'ADMIN@ITFLOW.COM', 'admin', '$2a$10$MNsNLmxb1HnkGgO56021eu.Er4omFxesT0CEm.FH2kKWGkLQNPpPC', NULL, NOW(), '1', '1');
INSERT INTO "ROLE" ("ID", "ROLE") VALUES ('1', 'ADMIN');
INSERT INTO "COMPANY" ("NAME", "DOCUMENT") VALUES ('IT FLOW', '000000000');
INSERT INTO "BRANCH" ("NAME", "COMPANY_ID") VALUES ('TECHNOLOGY', '1');
INSERT INTO "DEPARTMENT" ("NAME", "BRANCH_ID") VALUES ('IT', '1');
INSERT INTO "OCCUPATION" ("NAME") VALUES ('MANAGER');
INSERT INTO "DEVICE_CATEGORY" ("NAME", "ACTIVE") VALUES ('COMPUTER', '1');
INSERT INTO "SOFTWARE" ("NAME") VALUES ('SOFTWARE TEST');